package com.invest;


/**
* AdditionApp/AdditionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Friday, November 29, 2019 9:55:08 PM JST
*/

public interface AdditionOperations 
{
  int add (int a, int b);
  void shutdown ();
} // interface AdditionOperations
